print("Parabens")
print("Aqui vai um dinossauro!")
print("")
print("")
print("              __  ")
print("             / _) ")
print("            / /    ")
print("     .-^^^-/ /"    )
print("  __/       /"     )
print("< __.|_|-|_|")
print("")
print("")
print("E aqui vai um bolo!")
print("")
print("")
print("  . . . . . .")
print("  i i i i i i")
print("###############")
print("===============")
print("###############")
print("===============")
print("###############")
